# example Kubernetes deployment manifest
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskapp
  namespace: aleksacolovic
  labels:
      app: myflaskapp
  spec:
  replicas: 1
  selector:
    matchLabels:
      app: myflaskapp
  template:
    metadata:
      labels:
        app: myflaskapp
    spec:
      containers:
        - name: myflaskapp
          image: ${DOCKER_IMAGE}
          ports:
            - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 20
