# example Kubernetes service manifest
# if correctly configured you should be able to access the deployment on chosen nodePort (select one value randomly between 30000-32767)
apiVersion: v1
kind: Service
metadata:
  name: myflaskapp
  namespace: aleksacolovic
  labels:
    app: myflaskapp
spec:
  selector:
    app: myflaskapp
  ports:
    - name: http
      port: 80
      targetPort: 4000
      nodePort: 31111
  type: NodePort
